// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menu-open-bilingual'
  | 'menu-prefetch'
  | 'menu-prefetch-stop'
  | 'pref-title'
  | 'toolbar-open-bilingual';
