// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "readerPrefs": string;
      "apiBase": string;
      "apiKey": string;
      "apiModel": string;
      "apiConcurrency": number;
      "apiProviders": string;
      "grokPath": string;
      "grokModel": string;
      "grokEffort": string;
      "codexPath": string;
      "codexModel": string;
      "codexEffort": string;
      "claudePath": string;
      "claudeModel": string;
      "claudeEffort": string;
      "agentConcurrency": number;
      "agentTimeoutSec": number;
      "glossary": string;
      "batchChars": number;
      "mineruRoot": string;
      "mineruToken": string;
    };
  }
}
